Update windows-build.yml

diff --git a/.github/workflows/windows-build.yml b/.github/workflows/windows-build.yml
--- a/.github/workflows/windows-build.yml
+++ b/.github/workflows/windows-build.yml
@@ -45,7 +45,7 @@ jobs:
 
       - name: Install Dependencies
         run: |
-          wsl bash -c "set -e; sudo apt update; for i in {1..5}; do sudo apt install -y python3 python3-pip python3-venv unzip && break; echo 'APT failed, retrying (\$i)...'; sleep 10; done"
+          wsl bash -c "set -e; sudo apt update; for i in {1..5}; do sudo apt install -y python3 python3-pip python3-venv unzip gdisk && break; echo 'APT failed, retrying (\$i)...'; sleep 10; done"
 
       - name: Install Python requirements
         run: wsl pip3 install -r requirements.txt
@@ -57,4 +57,4 @@ jobs:
       - name: Check whether clean
         run: |
           wsl git status
-          wsl test -z \"\$(git status --porcelain --ignore-submodules)\"
+          wsl bash -c 'test -z "$(git status --porcelain --ignore-submodules)"'
