Update windows-build.yml

diff --git a/.github/workflows/windows-build.yml b/.github/workflows/windows-build.yml
--- a/.github/workflows/windows-build.yml
+++ b/.github/workflows/windows-build.yml
@@ -22,10 +22,6 @@ jobs:
         with:
           distro: Ubuntu
 
-      - name: Install Python
-        run: |
-          wsl bash -c "set -e; sudo apt update; for i in {1..5}; do sudo apt install -y python3 python3-pip python3-venv && break; echo 'APT failed, retrying (\$i)...'; sleep 10; done"
-
       - name: Set custom WSL mount root
         run: |
           wsl bash -c "echo -e '[automount]\nroot = /' | sudo tee /etc/wsl.conf"
@@ -36,6 +32,10 @@ jobs:
         uses: actions/checkout@v3
         with:
           submodules: recursive
+
+      - name: Install Python
+        run: |
+          wsl bash -c "set -e; sudo apt update; for i in {1..5}; do sudo apt install -y python3 python3-pip python3-venv && break; echo 'APT failed, retrying (\$i)...'; sleep 10; done"
 
       - name: Install Python requirements
         run: wsl pip3 install -r requirements.txt
@@ -54,13 +54,13 @@ jobs:
 
       - name: Build target
         run: |
-          $wsl_path = wsl wslpath -m $env:GITHUB_WORKSPACE
+          $wsl_path = wsl wslpath -u $env:GITHUB_WORKSPACE
           Write-Host "WSL path is $wsl_path"
           wsl bash -c "cd $wsl_path && make ${{ matrix.target }}-all"
 
       - name: Check whether clean
         run: |
-          $wsl_path = wsl wslpath -m $env:GITHUB_WORKSPACE
+          $wsl_path = wsl wslpath -u $env:GITHUB_WORKSPACE
           Write-Host "WSL path is $wsl_path"
           wsl bash -c "cd $wsl_path && git status"
           wsl bash -c "cd $wsl_path && test -z \"\$(git status --porcelain --ignore-submodules)\""
