Update windows-build.yml

diff --git a/.github/workflows/windows-build.yml b/.github/workflows/windows-build.yml
--- a/.github/workflows/windows-build.yml
+++ b/.github/workflows/windows-build.yml
@@ -43,9 +43,9 @@ jobs:
         with:
           submodules: recursive
 
-      - name: Install Python
+      - name: Install Dependencies
         run: |
-          wsl bash -c "set -e; sudo apt update; for i in {1..5}; do sudo apt install -y python3 python3-pip python3-venv && break; echo 'APT failed, retrying (\$i)...'; sleep 10; done"
+          wsl bash -c "set -e; sudo apt update; for i in {1..5}; do sudo apt install -y python3 python3-pip python3-venv unzip && break; echo 'APT failed, retrying (\$i)...'; sleep 10; done"
 
       - name: Install Python requirements
         run: wsl pip3 install -r requirements.txt
